import {
  Grid,
  GridItem,
  List,
  ListIcon,
  ListItem,
  Text,
  Flex,
  Heading,
  Progress,
  Image,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { ContentBox } from "../components/ContentBox";
import { Navigation } from "../components/Navigation";
import bioJson from "../data/bio.json";
import likeJson from "../data/like.json";
import skillJson from "../data/skill.json";
import historyJson from "../data/history.json";
import { CheckCircleIcon } from "@chakra-ui/icons";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        gridTemplateColumns="200px 1fr"
        height="100%"
        gridTemplateRows="1fr"
      >
        <GridItem>
          <Navigation />
        </GridItem>
        <Grid
          backgroundColor="#F5F5F5"
          padding={8}
          gridTemplateColumns="70% 1fr"
          gridTemplateRows="auto auto auto"
          gap="32px"
          alignContent="flex-start"
        >
          <Heading as="h1" fontSize="xl" gridColumn="1/3">
            Profile
          </Heading>
          <ContentBox title="Bio">
            <Grid gap="4">
              {bioJson.map((text, index) => {
                return <Text key={index}>{text}</Text>;
              })}
            </Grid>
          </ContentBox>
          <ContentBox title="History">
            <Grid gap="4">
              {historyJson.map(({ name, date, position }, index) => {
                return (
                  <Flex
                    gap={4}
                    key={index}
                    flexDirection="column"
                    paddingLeft={6}
                    borderLeft="10px solid #04565C"
                  >
                    <Text>{date}</Text>
                    <Text>{name}</Text>
                    <Text>{position}</Text>
                  </Flex>
                );
              })}
            </Grid>
          </ContentBox>
          <ContentBox title="Skill">
            <Grid gap={8}>
              {skillJson.map(({ name, value }, index) => {
                return (
                  <Grid gridTemplateColumns="200px 1fr" key={index}>
                    <Text>{name}</Text>
                    <Progress
                      value={value}
                      backgroundColor="#F7F1EC"
                      size="lg"
                      height="1.4rem"
                      borderRadius="5px"
                      sx={{
                        "& > div": {
                          background: "#FDBDA3",
                        },
                      }}
                    />
                  </Grid>
                );
              })}
            </Grid>
          </ContentBox>
          <ContentBox title="Like">
            <List spacing={3}>
              {likeJson.map((text, index) => {
                return (
                  <ListItem key={index}>
                    <ListIcon as={CheckCircleIcon} color="#04565C" />
                    {text}
                  </ListItem>
                );
              })}
            </List>
          </ContentBox>
        </Grid>
      </Grid>
    </>
  );
};

export default Home;
